color_range_list:
  black:
    max:
    - 50
    - 160
    - 160
    min:
    - 0
    - 0
    - 0
  blue:
    max:
    - 255
    - 255
    - 170
    min:
    - 0
    - 155
    - 0
  green:
    max:
    - 255
    - 100
    - 255
    min:
    - 0
    - 0
    - 130
  red:
    max:
    - 255
    - 255
    - 255
    min:
    - 0
    - 165
    - 120
  white:
    max:
    - 255
    - 255
    - 255
    min:
    - 150
    - 100
    - 100
  yellow:
    max:
    - 255
    - 255
    - 255
    min:
    - 45
    - 100
    - 170
